/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartidosIndexRouteImport } from './routes/partidos.index'
import { Route as EquiposIndexRouteImport } from './routes/equipos.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PartidosMatchIdRouteImport } from './routes/partidos.$matchId'
import { Route as JugadoresPlayerIdRouteImport } from './routes/jugadores.$playerId'
import { Route as EquiposTeamIdRouteImport } from './routes/equipos.$teamId'
import { Route as AdminReglasRouteImport } from './routes/admin.reglas'

const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidosIndexRoute = PartidosIndexRouteImport.update({
  id: '/partidos/',
  path: '/partidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposIndexRoute = EquiposIndexRouteImport.update({
  id: '/equipos/',
  path: '/equipos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidosMatchIdRoute = PartidosMatchIdRouteImport.update({
  id: '/partidos/$matchId',
  path: '/partidos/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const JugadoresPlayerIdRoute = JugadoresPlayerIdRouteImport.update({
  id: '/jugadores/$playerId',
  path: '/jugadores/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposTeamIdRoute = EquiposTeamIdRouteImport.update({
  id: '/equipos/$teamId',
  path: '/equipos/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReglasRoute = AdminReglasRouteImport.update({
  id: '/admin/reglas',
  path: '/admin/reglas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rankings': typeof RankingsRoute
  '/admin/reglas': typeof AdminReglasRoute
  '/equipos/$teamId': typeof EquiposTeamIdRoute
  '/jugadores/$playerId': typeof JugadoresPlayerIdRoute
  '/partidos/$matchId': typeof PartidosMatchIdRoute
  '/admin/': typeof AdminIndexRoute
  '/equipos/': typeof EquiposIndexRoute
  '/partidos/': typeof PartidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rankings': typeof RankingsRoute
  '/admin/reglas': typeof AdminReglasRoute
  '/equipos/$teamId': typeof EquiposTeamIdRoute
  '/jugadores/$playerId': typeof JugadoresPlayerIdRoute
  '/partidos/$matchId': typeof PartidosMatchIdRoute
  '/admin': typeof AdminIndexRoute
  '/equipos': typeof EquiposIndexRoute
  '/partidos': typeof PartidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rankings': typeof RankingsRoute
  '/admin/reglas': typeof AdminReglasRoute
  '/equipos/$teamId': typeof EquiposTeamIdRoute
  '/jugadores/$playerId': typeof JugadoresPlayerIdRoute
  '/partidos/$matchId': typeof PartidosMatchIdRoute
  '/admin/': typeof AdminIndexRoute
  '/equipos/': typeof EquiposIndexRoute
  '/partidos/': typeof PartidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rankings'
    | '/admin/reglas'
    | '/equipos/$teamId'
    | '/jugadores/$playerId'
    | '/partidos/$matchId'
    | '/admin/'
    | '/equipos/'
    | '/partidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rankings'
    | '/admin/reglas'
    | '/equipos/$teamId'
    | '/jugadores/$playerId'
    | '/partidos/$matchId'
    | '/admin'
    | '/equipos'
    | '/partidos'
  id:
    | '__root__'
    | '/'
    | '/rankings'
    | '/admin/reglas'
    | '/equipos/$teamId'
    | '/jugadores/$playerId'
    | '/partidos/$matchId'
    | '/admin/'
    | '/equipos/'
    | '/partidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RankingsRoute: typeof RankingsRoute
  AdminReglasRoute: typeof AdminReglasRoute
  EquiposTeamIdRoute: typeof EquiposTeamIdRoute
  JugadoresPlayerIdRoute: typeof JugadoresPlayerIdRoute
  PartidosMatchIdRoute: typeof PartidosMatchIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  EquiposIndexRoute: typeof EquiposIndexRoute
  PartidosIndexRoute: typeof PartidosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidos/': {
      id: '/partidos/'
      path: '/partidos'
      fullPath: '/partidos/'
      preLoaderRoute: typeof PartidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos/': {
      id: '/equipos/'
      path: '/equipos'
      fullPath: '/equipos/'
      preLoaderRoute: typeof EquiposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidos/$matchId': {
      id: '/partidos/$matchId'
      path: '/partidos/$matchId'
      fullPath: '/partidos/$matchId'
      preLoaderRoute: typeof PartidosMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jugadores/$playerId': {
      id: '/jugadores/$playerId'
      path: '/jugadores/$playerId'
      fullPath: '/jugadores/$playerId'
      preLoaderRoute: typeof JugadoresPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos/$teamId': {
      id: '/equipos/$teamId'
      path: '/equipos/$teamId'
      fullPath: '/equipos/$teamId'
      preLoaderRoute: typeof EquiposTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reglas': {
      id: '/admin/reglas'
      path: '/admin/reglas'
      fullPath: '/admin/reglas'
      preLoaderRoute: typeof AdminReglasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RankingsRoute: RankingsRoute,
  AdminReglasRoute: AdminReglasRoute,
  EquiposTeamIdRoute: EquiposTeamIdRoute,
  JugadoresPlayerIdRoute: JugadoresPlayerIdRoute,
  PartidosMatchIdRoute: PartidosMatchIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  EquiposIndexRoute: EquiposIndexRoute,
  PartidosIndexRoute: PartidosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
