/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PlantillaRouteImport } from './routes/plantilla'
import { Route as MisionesRouteImport } from './routes/misiones'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartidosIndexRouteImport } from './routes/partidos.index'
import { Route as EquiposIndexRouteImport } from './routes/equipos.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as JugadoresPlayerIdRouteImport } from './routes/jugadores.$playerId'
import { Route as EquiposTeamIdRouteImport } from './routes/equipos.$teamId'
import { Route as AdminReglasRouteImport } from './routes/admin.reglas'
import { Route as AdminDesempenoRouteImport } from './routes/admin.desempeno'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantillaRoute = PlantillaRouteImport.update({
  id: '/plantilla',
  path: '/plantilla',
  getParentRoute: () => rootRouteImport,
} as any)
const MisionesRoute = MisionesRouteImport.update({
  id: '/misiones',
  path: '/misiones',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidosIndexRoute = PartidosIndexRouteImport.update({
  id: '/partidos/',
  path: '/partidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposIndexRoute = EquiposIndexRouteImport.update({
  id: '/equipos/',
  path: '/equipos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const JugadoresPlayerIdRoute = JugadoresPlayerIdRouteImport.update({
  id: '/jugadores/$playerId',
  path: '/jugadores/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposTeamIdRoute = EquiposTeamIdRouteImport.update({
  id: '/equipos/$teamId',
  path: '/equipos/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReglasRoute = AdminReglasRouteImport.update({
  id: '/admin/reglas',
  path: '/admin/reglas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDesempenoRoute = AdminDesempenoRouteImport.update({
  id: '/admin/desempeno',
  path: '/admin/desempeno',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/misiones': typeof MisionesRoute
  '/plantilla': typeof PlantillaRoute
  '/rankings': typeof RankingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/desempeno': typeof AdminDesempenoRoute
  '/admin/reglas': typeof AdminReglasRoute
  '/equipos/$teamId': typeof EquiposTeamIdRoute
  '/jugadores/$playerId': typeof JugadoresPlayerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/equipos/': typeof EquiposIndexRoute
  '/partidos/': typeof PartidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/misiones': typeof MisionesRoute
  '/plantilla': typeof PlantillaRoute
  '/rankings': typeof RankingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/desempeno': typeof AdminDesempenoRoute
  '/admin/reglas': typeof AdminReglasRoute
  '/equipos/$teamId': typeof EquiposTeamIdRoute
  '/jugadores/$playerId': typeof JugadoresPlayerIdRoute
  '/admin': typeof AdminIndexRoute
  '/equipos': typeof EquiposIndexRoute
  '/partidos': typeof PartidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/misiones': typeof MisionesRoute
  '/plantilla': typeof PlantillaRoute
  '/rankings': typeof RankingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/desempeno': typeof AdminDesempenoRoute
  '/admin/reglas': typeof AdminReglasRoute
  '/equipos/$teamId': typeof EquiposTeamIdRoute
  '/jugadores/$playerId': typeof JugadoresPlayerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/equipos/': typeof EquiposIndexRoute
  '/partidos/': typeof PartidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/misiones'
    | '/plantilla'
    | '/rankings'
    | '/reset-password'
    | '/admin/desempeno'
    | '/admin/reglas'
    | '/equipos/$teamId'
    | '/jugadores/$playerId'
    | '/admin/'
    | '/equipos/'
    | '/partidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/misiones'
    | '/plantilla'
    | '/rankings'
    | '/reset-password'
    | '/admin/desempeno'
    | '/admin/reglas'
    | '/equipos/$teamId'
    | '/jugadores/$playerId'
    | '/admin'
    | '/equipos'
    | '/partidos'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/misiones'
    | '/plantilla'
    | '/rankings'
    | '/reset-password'
    | '/admin/desempeno'
    | '/admin/reglas'
    | '/equipos/$teamId'
    | '/jugadores/$playerId'
    | '/admin/'
    | '/equipos/'
    | '/partidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MisionesRoute: typeof MisionesRoute
  PlantillaRoute: typeof PlantillaRoute
  RankingsRoute: typeof RankingsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminDesempenoRoute: typeof AdminDesempenoRoute
  AdminReglasRoute: typeof AdminReglasRoute
  EquiposTeamIdRoute: typeof EquiposTeamIdRoute
  JugadoresPlayerIdRoute: typeof JugadoresPlayerIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  EquiposIndexRoute: typeof EquiposIndexRoute
  PartidosIndexRoute: typeof PartidosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantilla': {
      id: '/plantilla'
      path: '/plantilla'
      fullPath: '/plantilla'
      preLoaderRoute: typeof PlantillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/misiones': {
      id: '/misiones'
      path: '/misiones'
      fullPath: '/misiones'
      preLoaderRoute: typeof MisionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidos/': {
      id: '/partidos/'
      path: '/partidos'
      fullPath: '/partidos/'
      preLoaderRoute: typeof PartidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos/': {
      id: '/equipos/'
      path: '/equipos'
      fullPath: '/equipos/'
      preLoaderRoute: typeof EquiposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jugadores/$playerId': {
      id: '/jugadores/$playerId'
      path: '/jugadores/$playerId'
      fullPath: '/jugadores/$playerId'
      preLoaderRoute: typeof JugadoresPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos/$teamId': {
      id: '/equipos/$teamId'
      path: '/equipos/$teamId'
      fullPath: '/equipos/$teamId'
      preLoaderRoute: typeof EquiposTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reglas': {
      id: '/admin/reglas'
      path: '/admin/reglas'
      fullPath: '/admin/reglas'
      preLoaderRoute: typeof AdminReglasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/desempeno': {
      id: '/admin/desempeno'
      path: '/admin/desempeno'
      fullPath: '/admin/desempeno'
      preLoaderRoute: typeof AdminDesempenoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MisionesRoute: MisionesRoute,
  PlantillaRoute: PlantillaRoute,
  RankingsRoute: RankingsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminDesempenoRoute: AdminDesempenoRoute,
  AdminReglasRoute: AdminReglasRoute,
  EquiposTeamIdRoute: EquiposTeamIdRoute,
  JugadoresPlayerIdRoute: JugadoresPlayerIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  EquiposIndexRoute: EquiposIndexRoute,
  PartidosIndexRoute: PartidosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
